name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Add Target
      run: rustup target add thumbv7em-none-eabi
    - name: Build
      run: cargo build --verbose --target=thumbv7em-none-eabi
